apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  selector:
    app: myapp
  ports:
    - name: web
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: asvinwin123/angular-app
        ports:
        - containerPort: 80

